name: Deploy to Portainer

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: Build and Push Docker Image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login (GitHub Container Registry)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/lyttle-development/documentation:main .

      - name: Push Docker Image
        run: docker push ghcr.io/lyttle-development/documentation:main

  trigger-portainer-webhook:
    name: Trigger Portainer Webhook
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Call Portainer Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
          method: POST
